//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_iS3_ProjectContext : iS3Context
    {
        public DB_iS3_ProjectContext(string project)
            : base("DB_iS3_" + project, "Models.Project.DB_iS3_Project")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_DataSourceInfo> Base_DataSourceInfo { get; set; }
        public virtual DbSet<Base_DataSourceType> Base_DataSourceType { get; set; }
        public virtual DbSet<Monitoring_InstrumentInfo> Monitoring_InstrumentInfo { get; set; }
        public virtual DbSet<Monitoring_MonGroupInfo> Monitoring_MonGroupInfo { get; set; }
        public virtual DbSet<Monitoring_MonPointInfo> Monitoring_MonPointInfo { get; set; }
        public virtual DbSet<Monitoring_MonProjectInfo> Monitoring_MonProjectInfo { get; set; }
        public virtual DbSet<Project_ObjectsDefinition> Project_ObjectsDefinition { get; set; }
        public virtual DbSet<Project_ProjectInfo> Project_ProjectInfo { get; set; }
    }
}
