//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_iS3Context : iS3Context
    {
        public DB_iS3Context()
            : base("DB_iS3", "Models.Project.DB_iS3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_DataSourceInfo> Base_DataSourceInfo { get; set; }
        public virtual DbSet<Base_DataSourceType> Base_DataSourceType { get; set; }
        public virtual DbSet<Permission_RoleInfo> Permission_RoleInfo { get; set; }
        public virtual DbSet<Permission_Role_User> Permission_Role_User { get; set; }
        public virtual DbSet<Permission_UserInfo> Permission_UserInfo { get; set; }
        public virtual DbSet<Permission_User_Project> Permission_User_Project { get; set; }
        public virtual DbSet<Project_PersonnelInfo> Project_PersonnelInfo { get; set; }
        public virtual DbSet<Project_UnitInfo> Project_UnitInfo { get; set; }
        public virtual DbSet<System_ModuleInfo> System_ModuleInfo { get; set; }
        public virtual DbSet<System_ProjectList> System_ProjectList { get; set; }
    }
}
