//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geology_SoilProperties
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StratumSectionID { get; set; }
        public Nullable<int> StratumID { get; set; }
        public Nullable<double> w { get; set; }
        public Nullable<double> gama { get; set; }
        public Nullable<double> Kv { get; set; }
        public Nullable<double> Kh { get; set; }
        public Nullable<double> ccq { get; set; }
        public Nullable<double> faicq { get; set; }
        public Nullable<double> c_s { get; set; }
        public Nullable<double> fais { get; set; }
        public Nullable<double> a01_02 { get; set; }
        public Nullable<double> Es01_02 { get; set; }
        public Nullable<double> qu { get; set; }
        public Nullable<double> K0 { get; set; }
        public Nullable<double> cuu { get; set; }
        public Nullable<double> faiuu { get; set; }
        public Nullable<double> ccu { get; set; }
        public Nullable<double> faicu { get; set; }
        public Nullable<double> cprime { get; set; }
        public Nullable<double> faiprime { get; set; }
        public Nullable<double> E015_0025 { get; set; }
        public Nullable<double> E02_0025 { get; set; }
        public Nullable<double> E04_0025 { get; set; }
        public Nullable<double> Cu { get; set; }
        public Nullable<double> c { get; set; }
        public Nullable<double> fai { get; set; }
        public Nullable<double> Cs { get; set; }
        public Nullable<double> e { get; set; }
        public Nullable<double> av { get; set; }
        public Nullable<double> G0 { get; set; }
        public Nullable<double> ar { get; set; }
        public Nullable<double> br { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> Sr { get; set; }
    }
}
