//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geology_WaterProperties
    {
        public int ID { get; set; }
        public string BoreholeName { get; set; }
        public Nullable<double> Cl { get; set; }
        public Nullable<double> SO4 { get; set; }
        public Nullable<double> Mg { get; set; }
        public Nullable<double> NH { get; set; }
        public Nullable<double> pH { get; set; }
        public Nullable<double> CO2 { get; set; }
        public string Corrosion { get; set; }
        public Nullable<int> StratumSectionID { get; set; }
    }
}
