//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geology_ConfinedWater
    {
        public int ID { get; set; }
        public string BoreholeName { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> StrataSectionID { get; set; }
        public Nullable<double> TopElevation { get; set; }
        public Nullable<double> ObservationDepth { get; set; }
        public string StatumName { get; set; }
        public Nullable<double> Layer { get; set; }
        public Nullable<double> WaterTable { get; set; }
        public Nullable<System.DateTime> ObservationDate { get; set; }
    }
}
