//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geology_BoreholeStrataInfo
    {
        public int ID { get; set; }
        public string OBJECTID { get; set; }
        public Nullable<int> StratumSequenceInBorehole { get; set; }
        public Nullable<int> StratumSectionID { get; set; }
        public Nullable<int> SectionSequenceBorhole { get; set; }
        public string SectionSequenceStrata { get; set; }
        public Nullable<double> ElevationOfStratumBottom { get; set; }
        public Nullable<int> BoreholeID { get; set; }
        public Nullable<int> StratumID { get; set; }
    }
}
