//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geology_Strata
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string GeologicalAge { get; set; }
        public string FormationType { get; set; }
        public string Compaction { get; set; }
        public string ElevationOfStratumBottom { get; set; }
        public string Thickness { get; set; }
        public string Description { get; set; }
    }
}
