//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geology_PhreaticWater
    {
        public int ID { get; set; }
        public string SiteName { get; set; }
        public Nullable<double> AvBuriedDepth { get; set; }
        public Nullable<double> AvElevation { get; set; }
        public Nullable<int> StratumSectionID { get; set; }
    }
}
