//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.SqlClient;
    
    public partial class DB_iS3Entities : DbContext
    {
        public DB_iS3Entities()
            : base(Connect())
        {
        }
    
        public static string Connect()

        {
            SqlConnectionStringBuilder sqlString = new SqlConnectionStringBuilder()
            {
                DataSource = "rm-bp1pflt7a70cw8j7m9o.sqlserver.rds.aliyuncs.com,3433", // Server name
                InitialCatalog = "DB_iS3",  //Database
                UserID = "ts1002",         //Username
                Password = "Ts65986858",  //Password
                PersistSecurityInfo = true,
                IntegratedSecurity = true,
                MultipleActiveResultSets = true
            };

            //Build an Entity Framework connection string

            EntityConnectionStringBuilder entityString = new EntityConnectionStringBuilder()
            {
                Provider = "System.Data.SqlClient",
                Metadata = "res://*//Models.Project.Model1.csdl|res://*//Models.Project.Model1.ssdl|res://*//Models.Project.Model1.msl",
                ProviderConnectionString = sqlString.ToString()

            };
            return entityString.ConnectionString;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<System_ProjectList> System_ProjectList { get; set; }
    }
}
