//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring_MonData
    {
        public int ID { get; set; }
        public Nullable<int> MonPointID { get; set; }
        public Nullable<decimal> Reading { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<System.DateTime> SysTime { get; set; }
    }
}
