//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring_MonGroupInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> MonGroupType { get; set; }
        public string MonPointIDs { get; set; }
        public Nullable<int> MonProjectID { get; set; }
        public string RefSpecifications { get; set; }
        public string PerInfoIDs { get; set; }
        public string Remark { get; set; }
    }
}
