//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_RoleInfo
    {
        public Permission_RoleInfo()
        {
            this.Permission_Role_User = new HashSet<Permission_Role_User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<Permission_Role_User> Permission_Role_User { get; set; }
    }
}
