//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_ObjectsDefinition
    {
        public int ID { get; set; }
        public string Name_Chs { get; set; }
        public string Name_En { get; set; }
        public string Code { get; set; }
        public Nullable<int> Type { get; set; }
        public string Domain { get; set; }
        public Nullable<int> GISLayerID { get; set; }
        public Nullable<int> DBID { get; set; }
        public string TableNameSQL { get; set; }
        public string OrderSQL { get; set; }
        public string ConditionSQL { get; set; }
        public string Remark { get; set; }
    }
}
