//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_UnitInfo
    {
        public Project_UnitInfo()
        {
            this.Project_PersonnelInfo = new HashSet<Project_PersonnelInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Project_PersonnelInfo> Project_PersonnelInfo { get; set; }
    }
}
