//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SegmentLinings
    {
        public int ID { get; set; }
        public Nullable<short> OBJECTID { get; set; }
        public Nullable<double> Centroid_Z { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> RingNo { get; set; }
        public Nullable<double> MilageAsDesign { get; set; }
        public Nullable<double> DesignX { get; set; }
        public Nullable<double> DesignY { get; set; }
        public Nullable<double> DesignH { get; set; }
        public Nullable<int> SLTypeIDAsDesign { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
    }
}
