//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLQualityRecords
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> OBJECTID_1 { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> RingNo { get; set; }
        public string QualityDescription { get; set; }
        public string InspectionDate { get; set; }
        public string Repairment { get; set; }
    }
}
