//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLPostureRecords
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> OBJECTID_1 { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> RingNo { get; set; }
        public Nullable<double> SLHorizontalDeviation { get; set; }
        public Nullable<double> SLElevationalDeviation { get; set; }
        public Nullable<double> SLGapUp { get; set; }
        public Nullable<double> SLGapDown { get; set; }
        public Nullable<double> SLGapLeft { get; set; }
        public Nullable<double> SLGapRight { get; set; }
        public Nullable<double> SLGap1 { get; set; }
        public Nullable<double> SLGap2 { get; set; }
        public Nullable<double> SLGap3 { get; set; }
        public Nullable<double> SLGap4 { get; set; }
        public Nullable<double> SLGap5 { get; set; }
        public Nullable<double> SLGap6 { get; set; }
        public Nullable<double> SLGap7 { get; set; }
        public Nullable<double> SLGap8 { get; set; }
        public Nullable<double> HorizontalDiameter { get; set; }
        public Nullable<double> VerticalDiameter { get; set; }
        public Nullable<double> Diamter1 { get; set; }
        public Nullable<double> Diamter2 { get; set; }
        public string DeformationDescription { get; set; }
        public Nullable<System.DateTime> SLDate { get; set; }
        public string Uploader { get; set; }
    }
}
