//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_Segments
    {
        public int ID { get; set; }
        public Nullable<int> SLBaseTypeID { get; set; }
        public Nullable<double> StartAngle { get; set; }
        public Nullable<double> CentralAngle { get; set; }
        public string Code { get; set; }
    }
}
