//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLConstructionRecords
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<short> LineNo { get; set; }
        public Nullable<double> MilageAsBuilt { get; set; }
        public Nullable<int> SLTypeIDAsBuilt { get; set; }
        public Nullable<System.DateTime> ConstructionDate { get; set; }
        public Nullable<int> KeySegementPositionNum { get; set; }
        public Nullable<short> IsDataMissing { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RingNo { get; set; }
    }
}
