//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLConvergence
    {
        public int ID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<double> Milage { get; set; }
        public Nullable<double> LineNo { get; set; }
        public Nullable<int> RingNo { get; set; }
        public Nullable<double> HorizontalRad { get; set; }
        public Nullable<double> HorizontalDeviation { get; set; }
        public Nullable<double> VerticalRad { get; set; }
        public Nullable<double> VerticalDeviation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
