//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLSpall
    {
        public int ID { get; set; }
        public string OBJECTID { get; set; }
        public string StartMilage { get; set; }
        public string EndMilage { get; set; }
        public Nullable<int> MetroLine { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> StartRingNo { get; set; }
        public Nullable<int> EndRingNo { get; set; }
        public string SLCode { get; set; }
        public string LocalX { get; set; }
        public string LocalY { get; set; }
        public string Shape { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> Length { get; set; }
        public string Width { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Document { get; set; }
        public string Discription { get; set; }
    }
}
