//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLSettlement
    {
        public int ID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<double> Milage { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> RingNo { get; set; }
        public Nullable<double> InitialElev { get; set; }
        public Nullable<double> Elevation { get; set; }
        public Nullable<double> Increasement { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
    }
}
