//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_SLBaseType
    {
        public int OBJECTID { get; set; }
        public Nullable<int> SLBaseTypeID { get; set; }
        public string SLCategory { get; set; }
        public string SLShape { get; set; }
        public Nullable<int> SLNumOfSegments { get; set; }
        public Nullable<double> SLConicity { get; set; }
        public Nullable<double> SLThickness { get; set; }
        public Nullable<double> SLWidth { get; set; }
        public Nullable<double> SLOutDiameter { get; set; }
        public Nullable<double> SLInnerDiameter { get; set; }
        public Nullable<int> SLTotalKeyPos { get; set; }
    }
}
