//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_TunnelAxesPoints
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public byte[] Shape { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<double> Milage { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> Z { get; set; }
    }
}
