//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iS3.Server.Models.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_ProjectList
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CODE { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<int> DBID { get; set; }
        public string FileService { get; set; }
        public string AnalysisService { get; set; }
        public Nullable<int> DefaultMapID { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public string ModuleIDs { get; set; }
        public string Remark { get; set; }
    }
}
